# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    target-branch: main
    commit-message:
      include: scope
      prefix: '[Dependabot] '
    labels:
      - Dependency
    assignees:
      - glektarssza
    schedule:
      interval: weekly
      day: wednesday
      time: '12:00'
      timezone: Canada/Mountain
  - directories:
      - /
      - /app/
      - /packages/core/
      - /packages/logging/
    package-ecosystem: npm
    versioning-strategy: increase-if-necessary
    target-branch: main
    commit-message:
      include: scope
      prefix: '[Dependabot] '
    labels:
      - Dependency
    assignees:
      - glektarssza
    schedule:
      interval: weekly
      day: wednesday
      time: '12:00'
      timezone: Canada/Mountain
