packages:
  - ./app/
  - ./packages/*
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
requiredScripts:
  - build
  - clean
  - test
  - lint
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
trustPolicy: no-downgrade
preferWorkspacePackages: true
recursiveInstall: true
includeWorkspaceRoot: true
shellEmulator: true
savePrefix: ^
sharedWorkspaceLockfile: true
saveWorkspaceProtocol: true
