packages:
  - ./app/
  - ./packages/*
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
requiredScripts:
  - build
  - clean
  - test
  - lint
preferWorkspacePackages: true
recursiveInstall: true
includeWorkspaceRoot: true
