# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint
on:
  workflow_call:
    inputs:
      git-ref:
        description: |
          The Git reference from which to clone the project.

          This can be any valid Git commit-ish (e.g. a SHA, a ref, a tag, and so
          on).

          Defaults to the SHA that caused the workflow to be triggered. If that
          is unavailable the fully formed reference of the branch or tag that
          triggered the workflow is used. If that is unavailable the repository
          default branch is used.
        type: string
        required: false
        default: ${{github.sha || github.ref || github.event.repository.default_branch}}
    secrets:
      github-token:
        description: |
          The token to use to make authenticated calls to the GitHub API.
        required: false
env:
  GITHUB_TOKEN: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      # -- Needed to checkout the repository
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{inputs.git-ref}}
          lfs: true
          token: ${{env.GITHUB_TOKEN}}
      - id: setup-pnpm
        name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: ./package.json
          run_install: false
          standalone: false
          cache: true
          cache_dependency_path: ./pnpm-lock.yaml
      - id: setup-nodejs
        name: Setup NodeJS
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
          token: ${{env.GITHUB_TOKEN}}
      - id: install-dependencies
        name: Install dependencies
        run: pnpm -r install
      - id: lint
        name: Lint
        run: pnpm run lint
