# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: On Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    permissions:
      # -- Needed to checkout the repository
      contents: read
    strategy:
      fail-fast: true
      matrix:
        build-type:
          - development
          - production
    uses: ./.github/workflows/build.yaml
    with:
      build-type: ${{matrix.build-type}}
      upload-artifacts: true
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
  test:
    name: Test
    permissions:
      # -- Needed to checkout the repository
      contents: read
    uses: ./.github/workflows/test.yaml
    with:
      node-version: nvmrc
      package-manager: pnpm
      package-manager-version: packageManifest
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
  lint:
    name: Lint
    permissions:
      # -- Needed to checkout the repository
      contents: read
    uses: ./.github/workflows/lint.yaml
    with:
      node-version: nvmrc
      package-manager: pnpm
      package-manager-version: packageManifest
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
  spell-check:
    name: Spell Check
    permissions:
      # -- Needed to checkout the repository
      contents: read
    uses: ./.github/workflows/spell-check.yaml
    with:
      node-version: nvmrc
      package-manager: pnpm
      package-manager-version: packageManifest
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
